### ISSUE TITLE
Trying to Compile my first PSX Game

### ISSUE THREAD

**Issue by godreborn** [Soeiz/FNaF2-PS1-Project#1]
hello.  I tried to install mips and the [nugget + psyq sdk].  I was able to compile one of the hello worlds, but I get an error about no common.mk instantly with the make command on this project.  I have a feeling I'm missing something.

**Comment by godreborn** [comment]
I wasn't sure which common.mk to use, so I tried using the ones at the root of the hello_world repo, but it failed with a mips error.

**Comment by godreborn** [comment]
![image](https://github.com/user-attachments/assets/318c29f6-b735-49de-9280-d6d9b085081c)

here's the error:

**Comment by Soeiz** [comment]
Sorry for the delay ! It must be a RAM overflow, I can't update the github repository at the moment, but when I could I'll do it. The RAM for this game is 100%'d, meaning that even if you write some code it can give you this kind of errors. I'll try sometime and optimize the images to liberate some RAM
