### ISSUE TITLE
Another Issue Trying to Compile

### ISSUE THREAD

**Issue by godreborn** [Soeiz/FNaF2-PS1-Project#2]
I was able to get over that previous error (mind you, I'm using ubuntu 20.04 wslv2), but now I get this.  it may be a spelling issue, because linux is case-sensitive, and one of the tim files needed to be fully capitalized:

![image](https://github.com/user-attachments/assets/7c577baf-f557-4708-aec1-10425114cf88)

**Comment by Soeiz** [comment]
Try to delete "fnaf2.elf" "fnaf2.map" "fnaf2.o" "fnaf2.dep" and "fnaf2.ps-exe" these are temporary files and they may get you errors.

**Comment by Soeiz** [comment]
Try to delete "fnaf2.elf" "fnaf2.map" "fnaf2.o" "fnaf2.dep" and "fnaf2.ps-exe" these are temporary files and they may get you errors.

**Comment by godreborn** [comment]
okay, I got it.  it was several case-sensitive-related file names, mostly extensions that needed to be capitalized.

![image](https://github.com/user-attachments/assets/d8204252-2af6-44e1-82ec-68aa8fb4d8ba)
